### ISSUE TITLE
Greek tv 

### ISSUE THREAD

**Issue by fotis54** [Twilight0/repo.twilight0#2]
Δεν παίζουν τα ζωντανά καναλια

**Comment by bugatsinho** [comment]
θα διορθωθούν σύντομα...θέλω να πιστεύω...

**Comment by fotis54** [comment]
Πότε βλέπεις να ξαναπαιζουν?


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Spiros Moschopoulos <notifications@github.com> 
Datum: 04.07.16  00:26  (GMT+01:00) 
An: "Twilight0/repo.twilight0" <repo.twilight0@noreply.github.com> 
Cc: fotis54 <liantisf@yahoo.gr>, Author <author@noreply.github.com> 
Betreff: Re: [Twilight0/repo.twilight0] Greek tv (#2) 

θα διορθωθούν σύντομα...θέλω να πιστεύω...

**Comment by nplevris** [comment]
Το πρόβλημα παρουσιάστηκε με το version 0.0,8.2

**Comment by Twilight0** [comment]
To Greek TV δεν θα ανανεωθεί. Πλέον εργάζομαι επάνω στο AliveGR.
